[package]
name = "lezeh"
version = "0.0.1"
authors = ["Sendy Halim <sendyhalim93@gmail.com>"]
edition = "2018"
description = "Commands for lazy people like me"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33" }
failure = { version = "0.1.7" }

[build-dependencies]
built = "0.4"
