[package]
name = "lezeh"
version = "0.0.2"
authors = ["Sendy Halim <sendyhalim93@gmail.com>"]
edition = "2018"
description = "Commands for lazy people like me"
readme = "readme.md"
homepage = "https://github.com/sendyhalim/lezeh"
repository = "https://github.com/sendyhalim/lezeh"
keywords = ["cli", "developer-tools"]
categories = ["command-line-utilities"]
license-file = "license"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33" }
failure = { version = "0.1.7" }
phab-lib = { version = "0.1" }
config = { version = "0.10" }
serde = { version = "1.0.60", features = ["derive"] }
serde_json = { version = "1.0" }
futures = { version = "0.3" }
tokio = { version = "0.2" }
ghub = { version = "0.0.1" }

[build-dependencies]
built = "0.4"


[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "lezeh"
path = "src/bin/main.rs"
