# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Build on every tag release

name: build_artifacts

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            release_bin_name: lezeh.macos
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            release_bin_name: lezeh.linux
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Zip build result
        run: |
          zip --junk-paths ./target/${{ matrix.target }}/release/lezeh-${{ matrix.target }}.zip ./target/${{ matrix.target }}/release/lezeh
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/${{ matrix.target }}/release/lezeh-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
